# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.message_errors import MessageErrors  # noqa: F401,E501
from swagger_server import util


class Message(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, errors: List[MessageErrors]=None):  # noqa: E501
        """Message - a model defined in Swagger

        :param errors: The errors of this Message.  # noqa: E501
        :type errors: List[MessageErrors]
        """
        self.swagger_types = {
            'errors': List[MessageErrors]
        }

        self.attribute_map = {
            'errors': 'errors'
        }

        self._errors = errors

    @classmethod
    def from_dict(cls, dikt) -> 'Message':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Message of this Message.  # noqa: E501
        :rtype: Message
        """
        return util.deserialize_model(dikt, cls)

    @property
    def errors(self) -> List[MessageErrors]:
        """Gets the errors of this Message.


        :return: The errors of this Message.
        :rtype: List[MessageErrors]
        """
        return self._errors

    @errors.setter
    def errors(self, errors: List[MessageErrors]):
        """Sets the errors of this Message.


        :param errors: The errors of this Message.
        :type errors: List[MessageErrors]
        """

        self._errors = errors
