/**
 * Account Information
 * The Account Information API is used to retrieve account data. You can retrieve transaction information, the current balance of an account or details of the account itself. The API can be used by licensed third party service providers to access ABN AMRO accounts. An account can only be accessed when ABN AMRO's account holder authorizes this through the consent application. Please note that the sandbox environment will be available in Februari
 *
 * OpenAPI spec version: 3.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


/**
 * @param accountNumber The IBAN for which the balance was retrieved for example: '''NL12ABNA9999876523'''
 * @param balanceType Indicator of the type of balance that was retrieved for example: '''BOOKBALANCE'''
 * @param amount Amount including minus -9999999.99, unformatted. Negative in case of debit balance for example: '''-999.99'''
 * @param currency Currency of the mutation, 3 characters alphabetic ISO currency code (e.g. EUR or USD) as per ISO 4217 for example: '''EUR'''
 */
case class BalanceResponse (
  accountNumber: String,
  balanceType: Option[String],
  amount: Option[Double],
  currency: Option[String]
)

