/**
 * Account Information
 * The Account Information API is used to retrieve account data. You can retrieve transaction information, the current balance of an account or details of the account itself. The API can be used by licensed third party service providers to access ABN AMRO accounts. An account can only be accessed when ABN AMRO's account holder authorizes this through the consent application. Please note that the sandbox environment will be available in Februari
 *
 * OpenAPI spec version: 3.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


/**
 * @param reference Reference where to find more information on error
 * @param traceId The unique trace id sent for this request
 * @param code The unique error code key
 * @param message Understandable description for the error code key
 * @param category Category of error
 * @param status The http code of the error for example: '''123'''
 */
case class MessageErrors (
  reference: Option[String],
  traceId: Option[String],
  code: Option[String],
  message: Option[String],
  category: Option[String],
  status: Option[Integer]
)

