/**
 * Account Information
 * The Account Information API is used to retrieve account data. You can retrieve transaction information, the current balance of an account or details of the account itself. The API can be used by licensed third party service providers to access ABN AMRO accounts. An account can only be accessed when ABN AMRO's account holder authorizes this through the consent application. Please note that the sandbox environment will be available in Februari
 *
 * OpenAPI spec version: 3.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


/**
 * Transaction details
 *
 * @param bookDate The bookkeeping date of the mutation
 * @param amount Amount including minus -9999999.99, unformatted. Negative in case of debit transactions for example: '''10.15'''
 * @param descriptionLines Unformatted text entered by the user during the transaction. String array of up to nine lines of each 0 to 32 characters
 * @param counterPartyAccountNumber Counter account number. Will be empty if no counter account is found for the transaction (e.g an ATM withdrawal). for example: '''NL55INGB9999300517'''
 * @param currency Currency of the mutation, 3 characters alphabetic ISO currency code (e.g. EUR or USD) as per ISO 4217 for example: '''EUR'''
 * @param mutationCode Indicator for the type of transaction for example: '''654'''
 * @param counterPartyName Name associated with the counter account number for example: '''Petstore supplies'''
 * @param transactionId Unique id generated for every request for example: '''8297K5935164172S0AC'''
 * @param transactionTimestamp Timestamp of the transaction execution for example: '''2018-10-24-11:59:35.710'''
 * @param balanceAfterMutation Account balance after the current payment transaction for example: '''6941.18'''
 * @param status The status of the transaction. for example: '''EXECUTED'''
 */
case class TransactionResponseTransactions (
  bookDate: Option[date],
  amount: Option[Double],
  descriptionLines: Option[List[String]],
  counterPartyAccountNumber: Option[String],
  currency: Option[String],
  mutationCode: Option[String],
  counterPartyName: Option[String],
  transactionId: Option[String],
  transactionTimestamp: Option[String],
  balanceAfterMutation: Option[Double],
  status: Option[String]
)

